# Generated by Django 3.0.8 on 2020-07-19 06:04

from django.db import migrations

def create_techspec(apps, schema_editor):

    ProductModel= apps.get_model('product', 'Product')
    TechSpecModel = apps.get_model('product', 'TechSpec')

    for product in ProductModel.objects.all():

        instance, _ =TechSpecModel.objects.get_or_create(
            attribute = 'head',
            value ='100',
        )
        product.tech_spec = instance 
        product.save() 

class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200719_1356'),
    ]

    operations = [
        migrations.RunPython(create_techspec)
    ]
